# Generated by Django 3.0.3 on 2020-05-17 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mappingmapapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MapList',
            new_name='MapModel',
        ),
    ]
